name: Backend Tests

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      run: |
        cd backend
        python -m pytest -v
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}